### ISSUE TITLE
[custom-fields] Multilingual settings

### ISSUE THREAD

**Issue by marta-platoniq** [Platoniq/decidim-module-decidim_awesome#86]
Pel que dedueixo, tenim dos tipus de traduccions a abordar:

(1) La traducció dels títols dels camps, valors, textos d'ajuda, valor predeterminat... Sembla que aquest cas és el més complicat i he pensat, seria possible utilitzar la opció del Term Customizer de crear noves traduccions i en comptes d'introduir un text, poder introduir la clau de traducció? 

![image](https://user-images.githubusercontent.com/72607737/116520630-42f74800-a8d3-11eb-9f2d-6c5adb8e042e.png)

(2) La traducció dels warnings, errors, camp "other" al checkbox group... que això imagino que anirà amb el crowdin i és més senzill, oi? 

![image](https://user-images.githubusercontent.com/72607737/116519975-6b327700-a8d2-11eb-9b5e-a8fbea773646.png)

**Comment by Kagemaru** [comment]
I've thrown together a PoC for this.

Right now, I'm replacing all values with translations outside the admin panel if they match this regex: `/^!(\S.*\..*)$/`
So if it starts with an exclamation point and contains dot separated values, it is used as a translation key.

There might be a better syntax to denote translation keys (!translation.key!/%translation.key%)

Currently, it shows the keys in the admin panel, since I couldn't get it to not save the translation, but the key in the short time I've had.

I'm trying to gather thoughts about this way of handling it. Do you think this is a good way to handle it? Do you have improvement ideas?

Admin Preview:
![field_preview](https://user-images.githubusercontent.com/12155/122732576-b76bb900-d27c-11eb-8c9f-255a2fef3b19.png)

Admin Settings:
![field_settings](https://user-images.githubusercontent.com/12155/122732618-c05c8a80-d27c-11eb-9719-d918e83bf920.png)

Translation Key (in a local file here, could be term customizer too):
![translation_keys](https://user-images.githubusercontent.com/12155/122732647-c81c2f00-d27c-11eb-9393-21d7ab38174e.png)

User Preview:
![usage](https://user-images.githubusercontent.com/12155/122732788-e84bee00-d27c-11eb-9b9c-5603a6689157.png)

**Comment by microstudi** [comment]
Hi @Kagemaru thanks for starting this!

Actually, i was thinking more or less the same but just make the system capable of dealing with keys in a transparent way, if there's a translation for it, just show the translation, if not, the key.

Do you think that marking in some way (ie the ! char) is advisable for specific reason?

**Comment by Kagemaru** [comment]
The only problem I could see is if someone would be trying to use the language key as actual text (de/en). 
Though, now that I think of it, we can solve that with a bit regex too.
Other than that, I've mainly used it to clearly indicate what's a translation key and what isn't.

I'll try to make a version without it and test it for a bit.

**Comment by larsUE** [comment]
Now working on a live process here: https://mitwirken.stadt-zuerich.ch/processes/stadtidee/f/21/proposals/new?locale=de

**Comment by microstudi** [comment]
This is great! Things in production ensures quick bugfixing 😅 I'm gonna merge your pr #109 all right?
Then we will make a recap of what's missing in order to do the final release

**Comment by larsUE** [comment]
Just noticed that the multilingual setting doesn't work for amendments yet :/ and only displays the keys, which is quite ugly. Does anybody have some time to fix this?

@microstudi : something for your final release recap ;)

**Comment by microstudi** [comment]
@larsUE could yo try the last version of the branch `custom-fields`, I think amendments should be solved now (along with other things). Thanks!

**Comment by marta-platoniq** [comment]
Multilingual settings with term customizer are working fine for me, also for amendments.

BUT (there is always an annoying but) translation for warnings, validation errors, and the "other" field in checkbox group are not working. 
 
![image](https://user-images.githubusercontent.com/72607737/136200479-a0917b47-9fd5-44d6-82d7-1c87afbd1e31.png)

**Comment by larsUE** [comment]
Yes, I think these fields currently can't be translated. @Kagemaru do you have any more information?

**Comment by marta-platoniq** [comment]
I know @microstudi was working on it, will it be possible to translate those fields, Ivan?
